### ISSUE TITLE
EPIC: Include a relayer implementation

### ISSUE THREAD

**Issue by srdtrk** [cosmos/solidity-ibc-eureka#121]
## Description

Include a relayer implementation in this repo between Ethereum and Cosmos. This relayer implementation is intended to be used by service providers and/or frontends, as such, it will be built primarily as an RPC server, to which relayer users submit tx hashes which emit packets to be relayed.

## Requirements

- [x] Supports relaying Cosmos -> Ethereum via `solidity-ibc-eureka` and `sp1-ics07-tendermint`
- [x] Supports relaying Ethereum -> Cosmos via the `08-wasm` client we use.
- [x] Runs as an RPC server which can receive concurrent requests.
- [x] Supports batching via tx hashes.

## Automated e2e tests

- [x] Include a relayer test suite which tests the relayer. Not to replace manual relaying with the relayer in the main test suite.

## QA scenarios

- Relaying a single packet
- Relaying multiple packets
- Usage via an external team

## Tasks

- [x] #122
- [x] #127
- [x] #136
- [x] #140
- [x] #152
- [x] Relay 1 Recv packet from Ethereum to Cosmos
- [x] Add tests for batch tx and ack relaying from eth to Cosmos
- [x] Add timeout tests for relaying from eth to Cosmos
- [x] #153
- [x] #174
- [x] #179
- [x] #181

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged/assigned

**Comment by gjermundgaraba** [comment]
Initial implementation is done and can be verified in our e2e tests that use them for all relaying now. 

Next round of work is an iterative improvement process tracked in #200
