### ISSUE TITLE
Remove the operator

### ISSUE THREAD

**Issue by srdtrk** [cosmos/solidity-ibc-eureka#158]
## Requirements

The operator was initially built in the `sp1-ics07-tendermint` repository to deploy and test the sp1 light client. Since it is only capable of creating fixtures, it has become a hacky solution in the testing suite. 

The responsibilities of the operator should be given to individual relayer modules (which should be allowed to have custom RPC methods and possibly custom cli).

## Tasks
- [ ] Allow relayer modules to have custom RPC methods.
- [x] Move sp1-ics07 client creation to the `cosmos_to_eth` relayer module and remove client deployment script.
- [ ] Move sp1-ics07 proof creation methods to the `cosmos_to_eth` relayer module and generate the fixtures in e2e tests instead.
- [ ] Remove the operator

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
